export const ELEMENTERRA_PROGRAMM_ID =
  'ELEMisgsfkmp58w1byRvrdpGG1HcapQoCrmMJeorBCxq';

export const ELEMENTERRA_PROGRAM_CLAIM_PENDING_GUESS_DATA = 'J1gU5gpUd3E';

export const ELEMENTERRA_PROGRAM_ADD_TO_PENDING_GUESS_DATA_PREFIX = 'FTDA';

export const ELEMENTERRA_ELEMENTS_COLLECTION_ID =
  'CdES51P2ThUZsgAeqFG42k59QchQMWBR9hLLeUGeB2gL';

// Changes over time (do not use)
export const ELEMENTERRA_ELEMENTS_TREE_ID =
  '5mKidNUBYY2N22se94PvmF9YF5tUcJEgRAyNN4GiBbFY';

export const ADD_TO_PENDING_GUESS_COUNT = 4;

export const EARLY_ELEMENTERRA_PROGRAM_SOLT = 243925961;
export const EARLY_ELEMENTERRA_PROGRAM_TRANSACTION =
  '2RCF7SWrQtXtERvacNGHQzHZJ2jsZxRARxKhtxVdoR4bjmAH3V1Wc2UM1r5ANjP2QULpm2sYTrVFARekVzVaMqZH';

export const COLLECTIONS = {
  elementerra_rabbits: '4n4zLe1BcREy9XQyHwSMJJHR4YHn7AgP2dx4jL6X8GGR',
  elementerra_crystals: 'GsWtWwZLkS9Ee9Rb13MuTG3JfQx3nhh16ps36ZNEPcdW',
  elementerra_chests: '5LkHs8vFFkjgN6pnmPsvgUDn9iN4yj8h2qSoejuHtKoJ',
};
