export const ELEMENTERRA_PROGRAMM_ID =
  'ELEMisgsfkmp58w1byRvrdpGG1HcapQoCrmMJeorBCxq';

export const ELEMENTERRA_PROGRAM_CLAIM_PENDING_GUESS_DATA = 'J1gU5gpUd3E';

export const ELEMENTERRA_PROGRAM_ADD_TO_PENDING_GUESS_DATA_PREFIX = 'FTDA';
