export function cleanAndOrderRecipe(recipe: string[]): string[] {
  const r = recipe.map((e) => e.replaceAll(' ', '').toLowerCase());
  r.sort();
  return r;
}

export enum ElementName {
  mussel = 'mussel',
  brick = 'brick',
  mouse = 'mouse',
  grass = 'grass',
  heart = 'heart',
  battery = 'battery',
  flower = 'flower',
  safe = 'safe',
  horseshoe = 'horseshoe',
  pebble = 'pebble',
  keyboard = 'keyboard',
  puppet = 'puppet',
  ruby = 'ruby',
  oxygen = 'oxygen',
  sea = 'sea',
  gift = 'gift',
  acid = 'acid',
  house = 'house',
  stick = 'stick',
  diamond = 'diamond',
  boat = 'boat',
  woodenplank = 'woodenplank',
  blender = 'blender',
  greenhouse = 'greenhouse',
  tire = 'tire',
  bee = 'bee',
  wall = 'wall',
  ring = 'ring',
  gold = 'gold',
  spinach = 'spinach',
  honey = 'honey',
  car = 'car',
  kiwi = 'kiwi',
  zoo = 'zoo',
  bike = 'bike',
  iron = 'iron',
  money = 'money',
  spider = 'spider',
  silver = 'silver',
  cellphone = 'cellphone',
  lead = 'lead',
  nest = 'nest',
  toxic = 'toxic',
  statue = 'statue',
  internet = 'internet',
  smoothie = 'smoothie',
  fireplace = 'fireplace',
  bones = 'bones',
  string = 'string',
  compression = 'compression',
  duck = 'duck',
  chair = 'chair',
  organism = 'organism',
  rock = 'rock',
  engine = 'engine',
  key = 'key',
  blood = 'blood',
  chain = 'chain',
  thief = 'thief',
  loanshark = 'loanshark',
  blade = 'blade',
  leaf = 'leaf',
  gravel = 'gravel',
  bench = 'bench',
  wax = 'wax',
  microchip = 'microchip',
  vine = 'vine',
  coconut = 'coconut',
  egg = 'egg',
  web = 'web',
  hourglass = 'hourglass',
  necklace = 'necklace',
  horse = 'horse',
  flame = 'flame',
  piano = 'piano',
  race = 'race',
  steel = 'steel',
  palmtree = 'palmtree',
  temperedglass = 'temperedglass',
  fuel = 'fuel',
  salt = 'salt',
  mirror = 'mirror',
  window = 'window',
  pearl = 'pearl',
  freshwater = 'freshwater',
  banana = 'banana',
  rubber = 'rubber',
  wheel = 'wheel',
  monkey = 'monkey',
  mold = 'mold',
  marble = 'marble',
  garden = 'garden',
  soil = 'soil',
  aluminum = 'aluminum',
  toy = 'toy',
  computer = 'computer',
  silicone = 'silicone',
  sword = 'sword',
  carbon = 'carbon',
  brokenglass = 'brokenglass',
}

export const ELEMENTS_IDS = {
  '11111111111111111111111111111111': 'NOTHING',
  QWmroo4YnnMqYW3cnxWkFdaTxGD3P7vMSzwMHGbUzwF: 'sea',
  DKa2b2av5gCXbMjn2dKNYfkssphz3kZ4em3yRT3eSMPR: 'web',
  EHKEAMw4CEHywGXGaTeBS6nnpFePngXdwWo7rktp7q2R: 'chain',
  '9d225WyVJQPyuhh5y12QmYRTQkjc2EVThG7EhWoaeqmW': 'banana',
  '3Krep8kMJYRs2wEkpVxWfaYctMGyTD7rtoi9GSXu22VV': 'house',
  HsxAcS5ojYqKeRtydvCKfPYbggq2Mcua4RWo1ErRb4Ta: 'boat',
  '48Zc9ABHFbwtV7LzW1J6mrZxj5qNESKzL31bGLSAV4Cz': 'freshwater',
  '8eXSmqZBb9oSkuFVjTGA3Ri9yb8vWNpzfd4DnqX1kRY': 'car',
  DfeMFua1Z9uQXzfufzPNXNgdx4EQXHvC1s7cPtwAm44: 'race',
  GknUr2ZPFuTxdgGoAbfKnHmWMNaNmRd1MwbYEF4xcy6t: 'hourglass',
  AUcGCWfEx24yUEKCb6YPKnbp9o7ZqMpauA5P1dVLXhf1: 'ring',
  F9xHCqf1sVHicbTB7rU7kvPxR1k5xsj2ieNvmeNb2pD1: 'mussel',
  SoqiH4QZ8Ct63qDfFa6X2mCBZQpdmCtrgc7MBEh2X1s: 'internet',
  '7ErMFsjguCe5S8kz8G1Tiretgm1qrsFiqksqLeV8UN6C': 'brick',
  EHjxwjfNwqhqSinEw9Ub2j2sAPW4n3cm1ZQRmGFkj4LU: 'coconut',
  GhuK6v8Yu86Jqqdd7NhY9QRkHCgZqSPZYeYDxBBU7Eto: 'gift',
  '9rEXeyaf9XWgSSiFirsKhv6qzuf4SR6WBkJjCm2QqgSu': 'monkey',
  '7XfpTsaJ5zozKhZEZ9WuyZP7bvV84QFGAc7mkGjdmZj8': 'carbon',
  '4Dzt4beVk86fJhcr9ETdKYbaEN8xwmfaHLkgSYrxxLPn': 'toy',
  E3ECL6QQSYRtHtxXwWqcxcy83NF2Z6iE1C8nn2WYuHT2: 'wax',
  '5V8Hg24Qm8YF1DA9THdEbpgqQpdFweSkooZBrsrbjNTT': 'ruby',
  '3KQGEWX4o35mWM1cNK9C4FKVWu8jHkCvpTnZUp7iJpbb': 'spinach',
  EUzgt4B32RFpW4wqHYouLcfZx763LmVnaw3g8tunqkve: 'mirror',
  '8bo9t3LzAKy3vtzKtEttkbSGuw6Qx6r8xQ7tgKKz1YXP': 'gold',
  k7FaK87WHGVXzkaoHb7CdVPgkKDQhZ29VLDeBVbDfYn: 'rubber',
  '5sgE9FWoomgbiCSuCpbCMYMCqyDEPJ9dQ8A61AerfiXU': 'iron',
  AbWJhQqwEEepnuLtGawPa1HaLPXK1J8hd7dogYffFDTJ: 'statue',
  H389HfQqyZFsndRepdRPFBPoiMXNCvLx4giGBq4iJvRD: 'fuel',
  '7xw3VVC2tJe9Mp2Z6rBCezR5NH9aTix3vNPZ2bBQRyeN': 'aluminum',
  '9XAxC15g4bS8uVBqdEbdvQHjaVfaG1vxA5npA3hdQd57': 'bike',
  '5eCSVsgw4d2KZ5FDAhfM8a2oNseSaMQnjhDr5FzUpRxk': 'lead',
  '9wX3HhYqLY1x4UUWUmJ4YeuLiBynTNLs4p6AjoAzPzjG': 'bones',
  A3Uy8knCjFgY2UybFoH8ctCKSD7caA2hs3C7J65XKLom: 'gravel',
  BxyqriHA1D2rEDKdPv52s5zXQmQhpVytJzAbKRKRMRV2: 'mold',
  '2kys86WD89EgpL9SdaKCSjv233h5uLzKSfH3VgfuZSZ3': 'steel',
  Enmwv4ikJpD7jiUP1nyaLZsXRZp2k5qzK5SdyyD6iEg2: 'money',
  '9CT16sTEgZpVYdeKXvRQbnVGob31oDStimNevzmkd7XY': 'string',
  gBxS1f6uyyGPuW5MzGBukidSb71jdsCb5fZaoSzULE5: 'compression',
  DDro4VeSGuL6y3YwAkCjLVt9fFrjE2LzjS7XLFD3STxv: 'blender',
  HZirHe6MvuEGcQRxyzwKiUYPQxBhUmSxLLDUbhZYyHmg: 'horseshoe',
  AKWvKGp8sWRcA17oh7ku6HnratDAdc3CqvdoCBd9sSbP: 'palmtree',
  '8NvmdqBNGK55Vig2JXeQFdBwGfdvVoWoCkwryagr5DCt': 'safe',
  YMN9Qj5jPNp7j14VPcML1B6xGgcPWVZUGLFU3Mnyfaf: 'stick',
  '9j54zeyJ18MphRumjNEPp9HFdxk8wkUF8p1cH6EEF1u1': 'zoo',
  DjzKXTFeFMYxA4swJdbux8uGrQmwBysWsXN8vZPb6sKv: 'silver',
  '5eLMdWuCjBkiLR3T8UZexF2AZNH5a94GQhzoLMagAESc': 'puppet',
  '5zm9NAreQApk7MM7k3VYModU6HLgUxSKQyWakkMz12bD': 'silicone',
  BN4RJaUVZZiVSKsdQCWr5U43TxhQ1e421CkeWnw6xwYU: 'soil',
  FNEtxnsFTS7KhA3UZ2Vvt1w2pJM8kLTenRWizEDnEQ2i: 'marble',
  H1fBj3sdoRXiH41qMKQcBJwsiw2hfn9y3ufXmqFdRGtv: 'thief',
  CfitMQSWBBs8BhhNfsBzyFjkxLTQtLTQJq7sE3TeS2Vr: 'loanshark',
  GZZ9AkX2kGHz7vkKva8KWS5647wsyvRBdUFKCRxdzqkx: 'microchip',
  '2cRP7JJRCa6vHXXpMW1E2eXmAXHzmqagZsrBFCSU3aky': 'toxic',
  DnE8NniJJAtFZGCgyrv2eKu1r1JzK2NoNhNxqbimDvPq: 'pearl',
  p2Yicb86aZig616Eav2VWG9vuXR5mEqhtzshZYBxzsV: 'pebble',
  '4WCD514R6ZKhCEPzNZnP2zY5MN1ccH31jmbfPHYrdKdb': 'diamond',
  '2GnJyGqrwuQNJnUxBwvJZwDk2NB9a5R4mthdGScaQbj1': 'bee',
  AqsPiUhebYXs4p6kEN9bei3URimLvPhiU3EbWfas3fsQ: 'temperedglass',
  '8rtCcRxHuLTaqg5DkL8zDiLZLr4BfFvPD5pSWStXmdZM': 'sword',
  '7LZJrzsyLbc6egLpt4MUuDzmz5pfZfRgQRT5yQi2MqF8': 'chair',
  EZk23vDFr4koPE3jEH46XFBeVCdBgtMmF9228qVa1zeN: 'battery',
  DhrwVdyonMtRDTo3TnWDJuzQmqBzVkkBmKUxMnWQCzyR: 'organism',
  '7D6qSZ2DtT9GbNB8G6UFNV5VC3CyriMqhM8tdxta2WQb': 'spider',
  '3zre8B4GRwW2BDyNAp4tDLXsbJZ1wXCC1sSjy7izxcdV': 'keyboard',
  Brmx7NSt1nWBYkfHdNwHj5Hn3vtsVwUrJTcwba6oe2VD: 'computer',
  cGfHiC6Kgg3FpFZvgwGcswsCRtp4aBP2fzuXRQPizuN: 'brokenglass',
  Bzb4PtH8wiPoNPP47VKKvfXwGGfQrqQww4L9Ygkzs3YP: 'honey',
  '6731n8fD7ryoZJcAnHkmt97vMFNj77b8YGeK1sViJQDF': 'bench',
  '5Gd6U8waAHrcvAWdZrsA5KAvqrVK3798g8JcDc3wR3Z5': 'salt',
  '9Lt6wsPgZ4rvBkeiYjmDjhcduQ58dMxMoTFvWnQDuoew': 'woodenplank',
  Ct4JTqmGEHKLpFKRoby3U57hZdnsQ2rJCajry3BRNaWJ: 'rock',
  XCSx1REr5P9YxrVZaVtVGZKMgQaTumFT8xXN6PJvsyy: 'greenhouse',
  FGo9S5EChqJkbXcmwMKVZsKaGcZBkDnkQgiK47znH9Ks: 'kiwi',
  LbUiWL3xVV8hTFYBVdbTNrpDo41NKS6o3LHHuDzjfcY: 'flame',
  EhooUzL8jNfhugB64MPkzsd97sPw9f2jWJvz7STAhLmM: 'blood',
  '3jTk6Th2xtFAZAcAZV3KZiAhweEPp2vo7at1KUk9vz6k': 'key',
  '5bBdLTxpSCXbg5PPb6VQjAwW96F88gZz4rFt6tMz867k': 'oxygen',
  '7NrXzZuwMK66GNJLNhTYHrTAmzMPtRgMck3ZcKdivDfD': 'tire',
  ERgLCCgzLG27ySzwYrWz69ePbxEMYBdz9Xh8pf2oNCm2: 'cellphone',
  '87wsAcADR9DjVHuaWQCf7DxZY1sAG68vxVcEmsJMnhR5': 'vine',
  CTzDwHVuscvvoMQKvonGEHdhaFHKUGJZFSNHe2hHngnN: 'acid',
  '83ehwsorXXs9sExcaqWA5DXmw44H38LTo7Lpo3ndJ9ko': 'duck',
  '8ZpDTgBzNL2zqMt7yM9rP7SXhcXKs1SVhQ6FU6CzveqR': 'grass',
  '5ymGH8iWx2KXtBg7WqpBGcXTfvwNiNLV6VV1ZGhkR3FF': 'engine',
  ATDKkve8VvgvCPip7nvN9zjGqYJMNyQoA4vfo6iCwbjE: 'wheel',
  DtAf44uP9vHwXhSVzH9ob3D1EzC8fr1u5H96FwWzVv3w: 'nest',
  '7czG4T1Lp3fEHb6Ng4wSZy6yb9cAGtTV8fYaR5GPC742': 'egg',
  '9EvtjbvmekEEqxBxau5YkV3H4ewsgMVbhikxEDe1dZi8': 'necklace',
  H8RRvgF6USr75g7gPgBE6MdYL3p6Ymsr3S6F1v37C5g1: 'flower',
  '8ZSqxzCUAHfAZDv7gcRLxBKTSAqAQjdaExvHNecsaGwC': 'smoothie',
  Dz6B6ctQBSUC5ipDbAPiUy8ryC67iRt3ijFhv5FYQfti: 'heart',
  '9LoWpfUX3H34iRcFRj1p4fvdYLievSEX6VZ7ejw6ok9J': 'mouse',
  '5X9Gzj2PRwpvjfPdqG7kLvuVZ4HnPuSKjNDJ1Mn9mtTy': 'piano',
  St2KiJ5zXQQ99jE5XoYAADF2z4bPqST4nD1A2aKzQNN: 'window',
  '6WzfxKLBWKB5QHuuyvgCYg8i9hybhPEkZVvWR3oSmpS9': 'garden',
  CXVGsgKzUBcFkGyS9onFCag3DQyCmbYyVEv4hjCEpYKa: 'blade',
  GnwHMCQF2Pf1tbgHpM6pJZYec4GmA4ZfD2Ts5bs27BPx: 'fireplace',
  '2PtFPQYbGx1AFwRYRAZPg3k3hEe4bLrpk48sknjDQT9o': 'horse',
  '9chWWpqPnmZZuZMVTKyJZGFxkbyt8fq2WUKsZBk8Dkgc': 'wall',
  US517G5965aydkZ46HS38QLi7UQiSojurfbQfKCELFx: 'leaf',
};

export const ELEMENTS = [
  {
    name: 'spinach',
    tier: 2,
  },
  {
    name: 'keyboard',
    tier: 5,
  },
  {
    name: 'mirror',
    tier: 4,
  },
  {
    name: 'wax',
    tier: 3,
  },
  {
    name: 'soil',
    tier: 2,
  },
  {
    name: 'gold',
    tier: 4,
  },
  {
    name: 'banana',
    tier: 4,
  },
  {
    name: 'car',
    tier: 5,
  },
  {
    name: 'brick',
    tier: 2,
  },
  {
    name: 'temperedglass',
    tier: 1,
  },
  {
    name: 'window',
    tier: 2,
  },
  {
    name: 'rubber',
    tier: 0,
  },
  {
    name: 'wheel',
    tier: 3,
  },
  {
    name: 'sword',
    tier: 4,
  },
  {
    name: 'monkey',
    tier: 5,
  },
  {
    name: 'thief',
    tier: 6,
  },
  {
    name: 'house',
    tier: 5,
  },
  {
    name: 'palmtree',
    tier: 3,
  },
  {
    name: 'iron',
    tier: 2,
  },
  {
    name: 'silicone',
    tier: 3,
  },
  {
    name: 'heart',
    tier: 3,
  },
  {
    name: 'bench',
    tier: 3,
  },
  {
    name: 'organism',
    tier: 2,
  },
  {
    name: 'stick',
    tier: 0,
  },
  {
    name: 'necklace',
    tier: 5,
  },
  {
    name: 'statue',
    tier: 5,
  },
  {
    name: 'acid',
    tier: 3,
  },
  {
    name: 'money',
    tier: 5,
  },
  {
    name: 'computer',
    tier: 5,
  },
  {
    name: 'mouse',
    tier: 4,
  },
  {
    name: 'fuel',
    tier: 3,
  },
  {
    name: 'spider',
    tier: 3,
  },
  {
    name: 'horseshoe',
    tier: 4,
  },
  {
    name: 'duck',
    tier: 3,
  },
  {
    name: 'rock',
    tier: 1,
  },
  {
    name: 'toy',
    tier: 6,
  },
  {
    name: 'kiwi',
    tier: 4,
  },
  {
    name: 'aluminum',
    tier: 2,
  },
  {
    name: 'bike',
    tier: 5,
  },
  {
    name: 'chair',
    tier: 2,
  },
  {
    name: 'marble',
    tier: 2,
  },
  {
    name: 'string',
    tier: 2,
  },
  {
    name: 'blade',
    tier: 3,
  },
  {
    name: 'smoothie',
    tier: 5,
  },
  {
    name: 'nest',
    tier: 1,
  },
  {
    name: 'piano',
    tier: 5,
  },
  {
    name: 'mussel',
    tier: 3,
  },
  {
    name: 'tire',
    tier: 2,
  },
  {
    name: 'gravel',
    tier: 2,
  },
  {
    name: 'engine',
    tier: 4,
  },
  {
    name: 'garden',
    tier: 4,
  },
  {
    name: 'puppet',
    tier: 3,
  },
  {
    name: 'grass',
    tier: 3,
  },
  {
    name: 'oxygen',
    tier: 1,
  },
  {
    name: 'coconut',
    tier: 4,
  },
  {
    name: 'key',
    tier: 4,
  },
  {
    name: 'flame',
    tier: 0,
  },
  {
    name: 'salt',
    tier: 1,
  },
  {
    name: 'ruby',
    tier: 4,
  },
  {
    name: 'ring',
    tier: 4,
  },
  {
    name: 'freshwater',
    tier: 1,
  },
  {
    name: 'compression',
    tier: 0,
  },
  {
    name: 'blender',
    tier: 4,
  },
  {
    name: 'loanshark',
    tier: 6,
  },
  {
    name: 'microchip',
    tier: 4,
  },
  {
    name: 'flower',
    tier: 1,
  },
  {
    name: 'cellphone',
    tier: 5,
  },
  {
    name: 'egg',
    tier: 2,
  },
  {
    name: 'chain',
    tier: 3,
  },
  {
    name: 'steel',
    tier: 3,
  },
  {
    name: 'lead',
    tier: 2,
  },
  {
    name: 'vine',
    tier: 3,
  },
  {
    name: 'hourglass',
    tier: 2,
  },
  {
    name: 'race',
    tier: 6,
  },
  {
    name: 'fireplace',
    tier: 2,
  },
  {
    name: 'boat',
    tier: 5,
  },
  {
    name: 'toxic',
    tier: 1,
  },
  {
    name: 'sea',
    tier: 0,
  },
  {
    name: 'honey',
    tier: 4,
  },
  {
    name: 'internet',
    tier: 6,
  },
  {
    name: 'silver',
    tier: 2,
  },
  {
    name: 'battery',
    tier: 4,
  },
  {
    name: 'pearl',
    tier: 4,
  },
  {
    name: 'zoo',
    tier: 6,
  },
  {
    name: 'blood',
    tier: 2,
  },
  {
    name: 'pebble',
    tier: 0,
  },
  {
    name: 'safe',
    tier: 6,
  },
  {
    name: 'web',
    tier: 4,
  },
  {
    name: 'bones',
    tier: 1,
  },
  {
    name: 'woodenplank',
    tier: 1,
  },
  {
    name: 'carbon',
    tier: 1,
  },
  {
    name: 'brokenglass',
    tier: 0,
  },
  {
    name: 'wall',
    tier: 3,
  },
  {
    name: 'horse',
    tier: 5,
  },
  {
    name: 'mold',
    tier: 1,
  },
  {
    name: 'leaf',
    tier: 0,
  },
  {
    name: 'bee',
    tier: 2,
  },
  {
    name: 'diamond',
    tier: 3,
  },
  {
    name: 'greenhouse',
    tier: 3,
  },
  {
    name: 'gift',
    tier: 7,
  },
] as { name: ElementName; tier: number }[];
