export function cleanAndOrderRecipe(recipe: string[]): string[] {
  const r = recipe.map((e) => e.replaceAll(' ', '').toLowerCase());
  r.sort();
  return r;
}

export enum ElementName {
  air = 'air',
  water = 'water',
  fire = 'fire',
  earth = 'earth',
  lava = 'lava',
  rain = 'rain',
  smoke = 'smoke',
  energy = 'energy',
  steam = 'steam',
  mud = 'mud',
  pressure = 'pressure',
  life = 'life',
  dust = 'dust',
  fog = 'fog',
  wind = 'wind',
  heat = 'heat',
  ocean = 'ocean',
  pond = 'pond',
  stone = 'stone',
  ash = 'ash',
  river = 'river',
  time = 'time',
  cloud = 'cloud',
  coal = 'coal',
  metal = 'metal',
  tornado = 'tornado',
  worm = 'worm',
  hotsprings = 'hotsprings',
  sun = 'sun',
  mountain = 'mountain',
  frost = 'frost',
  swamp = 'swamp',
  clay = 'clay',
  oil = 'oil',
  fossil = 'fossil',
  sand = 'sand',
  wave = 'wave',
  seed = 'seed',
  magnet = 'magnet',
  glass = 'glass',
  snow = 'snow',
  solarpanel = 'solarpanel',
  windmill = 'windmill',
  bottle = 'bottle',
  alcohol = 'alcohol',
  gasoline = 'gasoline',
  telescope = 'telescope',
  furnace = 'furnace',
  dam = 'dam',
  storm = 'storm',
  squid = 'squid',
  nail = 'nail',
  gas = 'gas',
  paint = 'paint',
  volcano = 'volcano',
  coral = 'coral',
  sound = 'sound',
  sky = 'sky',
  tree = 'tree',
  desert = 'desert',
  fireextinguisher = 'fireextinguisher',
  plastic = 'plastic',
  plant = 'plant',
  antenna = 'antenna',
  balloon = 'balloon',
  blizzard = 'blizzard',
  wood = 'wood',
  umbrella = 'umbrella',
  electricity = 'electricity',
  apple = 'apple',
  cloth = 'cloth',
  meteor = 'meteor',
  cactus = 'cactus',
  sugar = 'sugar',
  wire = 'wire',
  explosion = 'explosion',
  music = 'music',
  ice = 'ice',
  ink = 'ink',
  island = 'island',
  paper = 'paper',
  dolphin = 'dolphin',
  bean = 'bean',
  lightning = 'lightning',
  fireworks = 'fireworks',
  beach = 'beach',
  tequila = 'tequila',
  hail = 'hail',
  blueprint = 'blueprint',
  hammer = 'hammer',
  rod = 'rod',
  coffee = 'coffee',
  art = 'art',
  tshirt = 'tshirt',
  icestorm = 'icestorm',
  fish = 'fish',
  yacht = 'yacht',
  party = 'party',
  coin = 'coin',
  whale = 'whale',
}

export const ELEMENTS_IDS = {
  '11111111111111111111111111111111': 'NOTHING',
  Bw4iN1gCvzmdiY9WfuEG1QJaxheTXif2fxuqQ5KQR2zT: 'water',
  DyYYN86vMZy6E8MVYEcrRTHwMJk5z66iDTPhHBYAafc2: 'earth',
  AqLM9JqF5wv5DZynY8CducahkB7JWPxWpDL29TPRwmNV: 'air',
  H1PLKchzLBgMNMnHLV15NScrMoXJXkgbCog2WnLxzjHn: 'fire',
  '3MmjYjFg9aB3br1mcfkToWSZH5o8jPSsursmUjgyy9F4': 'steam',
  '8B3cmtrNHzJi2z9HowdEuRowHoRXoVmpyMdytruDvJD5': 'mud',
  '9buezJaSwJy4jBoi7PPnmuKvuuUNxboZ8WMZH4ZjFdPh': 'smoke',
  HGkChvYGKSgGSt9fvtQmg8w6LEhKfhrNNVJL8YiSDbGs: 'heat',
  J5BuNGjzFoiPshShhWw5UoQDe7Uh5fXkebYuJn9QPtQY: 'fog',
  HjVoDDKz5VtzDTVDBNhWMGUhxG4MnNNRNtnZ6eHDcqyN: 'dust',
  '94cdHPXm5Rv5TCMg4YD5f9zXXXkmtX9suehAEHk8qkAA': 'energy',
  GA9jgGMRyr4n9UufmhQQqokztPjrDabcv5MYMGaR2fst: 'lava',
  '9uMzGd7onhKSJrhXvR5mca3XPMwZwx4PzooCVFkDNX9U': 'pressure',
  G6XyoAP5Tdz5WQPba995zhqddx8UVnJrRXG8W8P1S9fj: 'life',
  '7t75yYTPccVXj8sUenJKmEuM9gvncisyPTs5B13jdteG': 'wind',
  AQ7wz5m6sq25QTTWHcNPzR6SueBoQK4oGVqYhRizt6id: 'rain',
  FNVYqGvw6aDT15kQ3VUCpLvSnJLgQvGFzAt258MZTrBc: 'mountain',
  DieM3wCppu9EWjCw7wC7KGFtXuFz4w3WiyJJJChvhWY2: 'seed',
  EXKd8ZUxo24eXNLcwTStEiJH9RzFLrMTBQ2isYqZrTUT: 'hot springs',
  CyXVDUA7BZktv47C57HjJPhpyfgm97SJ5DwF9yfyJkJx: 'time',
  GA5cPSrYX6jooTkYyiDPxE8P5vBo47yu61s6P6vVrZAu: 'pond',
  '4R3yxdiCxnaBGF39jfXh2Q4iBNFm2DZMBotgUQpBECri': 'sun',
  AvfdrjvZ7BbjvpbStnt2vnV9E8Sfftzoz2zULvMhGaXP: 'coal',
  '4eTiHoeVGGFiU4CXfFjpbnAw5uZAqCgTvYqMscMddPYy': 'fossil',
  EQ8HPyhBB3ydbEz6kcBzYJUowaf1oxfY4BVqReydPCY2: 'tornado',
  '6bPKCgkdGgLSbvgeK1N96PKb5yZTKFAAEkn1Go4aGznZ': 'swamp',
  E6H62J4Dc4Pdg3SvmLT9jEEr4RiVxae5UNWT9prvBscJ: 'glass',
  '4cqqhRdUo31vtFJ6ntAvhBCu2XX5fNih7YRbVJJcESyB': 'sand',
  GCS2XqRiwMQTrQmixVeGW8Baw5vtchGvz94aPXQf2x6a: 'river',
  BM1hmtBKMRsu86Qr8zCp2apLaYBffbz8Pd6fF3DJJrin: 'metal',
  EqNfCMEDCu7VgnvRjdHNA5K3XZp2UrX25aWucbypv9pB: 'frost',
  BJr1atzAntztrxe7ybF2BaStWaf6PBXmRm2q3Fo3xsfC: 'cloud',
  G7rcTo7CZixMRBt2ESpajhCTA5rRYV9Wo9NnM9wS6AX2: 'magnet',
  '4Dyo7bLPe6h8hYdokHkYGrXXkpv81cLmCDWjtZZkuQ81': 'oil',
  BLXAGYyQf6Y27cgxzyXV9Hmgs2ZtvN4tGD1NtzazBEcm: 'clay',
  '4bsJxjy3VwYJr8opafB7PaebPsuTuPkbBLqzX8D1DkmU': 'ocean',
  E3WQQBwTs5zwzJLE4YCR9ddLQMLSphbJZrFhEfdPp1hE: 'worm',
  '4uakH9eP6prVhMUWEo6bnyFLMszzv1uEBW5RRF2xAVsY': 'snow',
  GibnswwWKKnrb6RnL8BLm5ACmEYG2DGebHSvfo6sw6YD: 'wave',
  ASoB6UKv46ta7hUyamAGDAuCVDhmRLo6Wv9psjKPP7BZ: 'ash',
  CkrtWvNQ6CAYhtMLupAs3VxXWnyN2C4qnSZ3YW7wdznv: 'stone',
  Ateg9mfDeHNN956k7v7bqU7QuGYdZkx8vEtJWviWLTKY: 'storm',
  '9uVafvVHc3axupwXraUMjgeQF64W9CKTSWmdeiQ7qTgY': 'paint',
  DtCo7UbULMnkJCHgf5iNHAWaHbF9DZjSBvDqF1JeiL4T: 'dam',
  '96rJpByuWXnzxT1gPvf8u8Pz9CE3fzCh5L323GbwGyV2': 'gasoline',
  jSiiGafD19RmxriAsKDHB1oWxfGugMaUvsKFtgREDGW: 'alcohol',
  '8Ut1nez6UuNAqr4dbMojqZQqFULrMdM8ZD6svTNH83BB': 'plant',
  FgeDexGkmFiUT6gjJE3P7hRTwY7ggw1C6r8coMpuxGSz: 'gas',
  AnFjJ8JxGRiEjnTwyjryrx63MTJcT4Y3wHtdUD6XedDe: 'solar panel',
  ErcpVHWjge8iiqtUsdpVf1vnhnLD5LNUvWR55HE45YHg: 'desert',
  GZxjXx9Nq72TVNVp5SRXatp2ykeQPzYB5BcjqCwQ2ZAN: 'bottle',
  '4apGySpNYbbGQDQdMk3LK7HcttuA5sxcTuHvdqKwS7CN': 'coral',
  WhCc614Ja7YPeF1YQVJ7MHvTvmfChEDTtig7MgqQn7T: 'volcano',
  Brci1cUALcMpb6aPCpzqrxYpK6LRza6KtoMGxjCZuiA4: 'nail',
  '4BBKuBxSAPJW1Ew1GT1YBVu4CyjcLHg5kfWxKwk5dKVU': 'furnace',
  '4eUG77yrhNiETCHH4dLn2x87sqWf4YVSY6GddbuMWhhH': 'squid',
  '88pZ1uii9SgHM596JNXKfbUQVSbnbz9yR8Yn8TaTXYsr': 'telescope',
  '85zYDe99HP1EPzP8kji9ZyyWuPnieh8J2e5WdhhGcYuQ': 'plastic',
  AhWaSxPLyBDQgrBdYuFb9yNMG63P7QfhxZRGt1HB8qJK: 'sky',
  AAnKWqXFkvhpxxf1vUxiysUVdjUE7JpwKy3vJdzkYfEA: 'fire extinguisher',
  '8reMp7L3yQrxJScfZoYEbJyy35gfAmLjBcp2tsXsxqy2': 'sound',
  '3LZiaK8zz24xsqdm2WeayJgSgpAcWuurojQLTG2AyPca': 'tree',
  FJJ2WtgHmnBVmUPT1BTAftD8F8vTYzQM8ipk3xdZ6AAG: 'windmill',
  '8wfBfYP79aUgtvhQqPLYQscBsZTp7LVHrYeQbzMaUoq9': 'umbrella',
  '3CaE6wEo9FNCcbCAomhybe3cBJLHdmWo1JmFP35LZGK5': 'wire',
  DFkgZEPac7RE5fWDpAjoW3mgESx9uC7pSMecDnPtJuWv: 'apple',
  '6u3upjYaKZ7dbGbussBgH8dymvhFXubK5ezzUQUndzfo': 'cloth',
  CVebn1dMzEzXZYSL5rqUk4CHUdr7mGF9KQEYwdqhuJeF: 'cactus',
  '7FgPFgukiwUpWohs9oMHheUvmZXSnx4RoVf441psuNVU': 'antenna',
  '35wx7NFpkDXFMj48A6qzY4nnGnJtWXGnUH7d89EM3oQ9': 'dolphin',
  E11serm1bsXBzEhJvKkUB2Wy5dQdqfpbHzAi1oCEzRK3: 'ink',
  EMga9t1N42gVPTkU4VGiqB8LMimB8cW2DcSdotUbpXU9: 'explosion',
  '5aqsZfV2PYVQu6QTvQEFtskeFbCKJxfghuUN7fDGUeKw': 'music',
  '7QxmAo92fPcpDADEVHxFAfd1BsdyZjhwUbh8wPLHbUVN': 'island',
  '29nme3KdLnYw1EBTgMBZXLxz8AfVBPJh68HBZGj73L4j': 'wood',
  BaNCDmKixZDBcC3nDNgYEiCwLUCH6wdvNW2vzTyb8cc5: 'bean',
  '2r8endBMp6jhc9JeBmyvnx8xoZN8MmqeX1uPixasP3bM': 'electricity',
  a3QvganvQ8Pdg2Czvhbp1R9R82FZ8u2Rk4VrF5UNLJw: 'balloon',
  C8U9VkxDZ9U85AV9FbHcW81x3KVFWWwpXgeRDabd3Yvm: 'blizzard',
  AsM2DKsLuDG1gYJEgxBbXUByqFXQeUGBLzF2MEpMkcNf: 'paper',
  '7kK6QKQYeST1yoskEq4QsxRh8dSFZRUQyajdZ8AbLKs4': 'ice',
  '68MmavdwYeGhwT4ADe8WcXzcqjk8EXPKQ36P9r79T5kj': 'sugar',
  '9bU4fJd6r1y5xaREi9ryMrtSVmet4UPwnf8HXjDMxP4T': 'meteor',
  AH3WV4iegL9TNedBD43sok2YKwV6g8E2h6WMNT8TaBpz: 'art',
  GW3G1KUaEUguvNRxwWv7JryNFbtaGSoziQMP5erMLmbB: 'blueprint',
  DPWmuzMaTYMJE35ka3X3XBRZUkP2AZ3QoWybP34EHhnG: 'hail',
  '6rKGq1E3k8t5eiUtAzfapGTMtvfLcmZe4jz3S6Ao5gfa': 'tequila',
  B4WBw6sikztikGu9PUqjS5rUoCjJfgS7eEaoLzTnVPoi: 'coffee',
  GdpTQSVfPEwtDx2sz6rbd9jD75WTK6rsnSXZbnedXU9V: 'rod',
  '6cwyx3Xn91n1k6gxRn61ihmjDNqzdPnSDnnJVW47WZt5': 'hammer',
  EL6NpwrApY4xji616XVsHXeUs7TSrkW3GLvvJWhTByhp: 'fireworks',
  DinReJZBbhjHc71SCk5zakJU1xoCm1ZLexdBSf82g6f5: 'lightning',
  C1PgMZxqeAHEuPgF3DETCnjp4b5qGEVnNf8urxKNsyB7: 'beach',
  GsTfxoMrBPpDFpc2x5i3ZXiRKSTYmzhSTXtYzsjDRDcv: 'party',
  eQVxSBvdpnFgGXZDu5LcAtgZu7WKS1QvvrgaPo1QT8A: 'fish',
  '2FAbvaZgyUcmKQnYG2GFKw763oc97ASrdxe8UUroL96Q': 'ice storm',
  D2JbuYtzcYpK6oPqQD7NHQLDRSeUJ2RVYzUDfs66xZum: 't shirt',
  '3kVJif6Z9ZfHCN1pZzAnif3p1adHXqtfnDuMbxy65G2t': 'coin',
  '6Jj9Ys3GLbQGPgXW3vj3rF4LSEAMvJ6SNH7ai9zHH1sm': 'yacht',
  uYR4GQ8Tf2m8eog2ApABZUYUmcGypgg2McSfyFHvVxH: 'whale',
};

export const ELEMENTS = [
  {
    name: 'water',
    tier: 0,
  },
  {
    name: 'fire',
    tier: 0,
  },
  {
    name: 'earth',
    tier: 0,
  },
  {
    name: 'air',
    tier: 0,
  },
  {
    name: 'dust',
    tier: 1,
  },
  {
    name: 'steam',
    tier: 1,
  },
  {
    name: 'smoke',
    tier: 1,
  },
  {
    name: 'wind',
    tier: 1,
  },
  {
    name: 'mud',
    tier: 1,
  },
  {
    name: 'lava',
    tier: 1,
  },
  {
    name: 'pressure',
    tier: 1,
  },
  {
    name: 'life',
    tier: 1,
  },
  {
    name: 'energy',
    tier: 1,
  },
  {
    name: 'heat',
    tier: 1,
  },
  {
    name: 'rain',
    tier: 1,
  },
  {
    name: 'fog',
    tier: 1,
  },
  {
    name: 'worm',
    tier: 2,
  },
  {
    name: 'clay',
    tier: 2,
  },
  {
    name: 'cloud',
    tier: 2,
  },
  {
    name: 'frost',
    tier: 2,
  },
  {
    name: 'mountain',
    tier: 2,
  },
  {
    name: 'pond',
    tier: 2,
  },
  {
    name: 'time',
    tier: 2,
  },
  {
    name: 'ash',
    tier: 2,
  },
  {
    name: 'metal',
    tier: 2,
  },
  {
    name: 'fossil',
    tier: 2,
  },
  {
    name: 'glass',
    tier: 2,
  },
  {
    name: 'ocean',
    tier: 2,
  },
  {
    name: 'sun',
    tier: 2,
  },
  {
    name: 'stone',
    tier: 2,
  },
  {
    name: 'sand',
    tier: 2,
  },
  {
    name: 'tornado',
    tier: 2,
  },
  {
    name: 'oil',
    tier: 2,
  },
  {
    name: 'magnet',
    tier: 2,
  },
  {
    name: 'river',
    tier: 2,
  },
  {
    name: 'hotsprings',
    tier: 2,
  },
  {
    name: 'coal',
    tier: 2,
  },
  {
    name: 'swamp',
    tier: 2,
  },
  {
    name: 'seed',
    tier: 2,
  },
  {
    name: 'snow',
    tier: 2,
  },
  {
    name: 'wave',
    tier: 2,
  },
  {
    name: 'tree',
    tier: 3,
  },
  {
    name: 'nail',
    tier: 3,
  },
  {
    name: 'volcano',
    tier: 3,
  },
  {
    name: 'telescope',
    tier: 3,
  },
  {
    name: 'sound',
    tier: 3,
  },
  {
    name: 'storm',
    tier: 3,
  },
  {
    name: 'desert',
    tier: 3,
  },
  {
    name: 'alcohol',
    tier: 3,
  },
  {
    name: 'sky',
    tier: 3,
  },
  {
    name: 'plastic',
    tier: 3,
  },
  {
    name: 'gas',
    tier: 3,
  },
  {
    name: 'dam',
    tier: 3,
  },
  {
    name: 'bottle',
    tier: 3,
  },
  {
    name: 'gasoline',
    tier: 3,
  },
  {
    name: 'windmill',
    tier: 3,
  },
  {
    name: 'coral',
    tier: 3,
  },
  {
    name: 'furnace',
    tier: 3,
  },
  {
    name: 'solarpanel',
    tier: 3,
  },
  {
    name: 'plant',
    tier: 3,
  },
  {
    name: 'fireextinguisher',
    tier: 3,
  },
  {
    name: 'paint',
    tier: 3,
  },
  {
    name: 'squid',
    tier: 3,
  },
  {
    name: 'ice',
    tier: 4,
  },
  {
    name: 'meteor',
    tier: 4,
  },
  {
    name: 'balloon',
    tier: 4,
  },
  {
    name: 'cactus',
    tier: 4,
  },
  {
    name: 'music',
    tier: 4,
  },
  {
    name: 'bean',
    tier: 4,
  },
  {
    name: 'sugar',
    tier: 4,
  },
  {
    name: 'explosion',
    tier: 4,
  },
  {
    name: 'island',
    tier: 4,
  },
  {
    name: 'electricity',
    tier: 4,
  },
  {
    name: 'wood',
    tier: 4,
  },
  {
    name: 'wire',
    tier: 4,
  },
  {
    name: 'apple',
    tier: 4,
  },
  {
    name: 'dolphin',
    tier: 4,
  },
  {
    name: 'antenna',
    tier: 4,
  },
  {
    name: 'cloth',
    tier: 4,
  },
  {
    name: 'umbrella',
    tier: 4,
  },
  {
    name: 'paper',
    tier: 4,
  },
  {
    name: 'blizzard',
    tier: 4,
  },
  {
    name: 'ink',
    tier: 4,
  },
  {
    name: 'rod',
    tier: 5,
  },
  {
    name: 'beach',
    tier: 5,
  },
  {
    name: 'blueprint',
    tier: 5,
  },
  {
    name: 'art',
    tier: 5,
  },
  {
    name: 'fireworks',
    tier: 5,
  },
  {
    name: 'tequila',
    tier: 5,
  },
  {
    name: 'hammer',
    tier: 5,
  },
  {
    name: 'lightning',
    tier: 5,
  },
  {
    name: 'hail',
    tier: 5,
  },
  {
    name: 'coffee',
    tier: 5,
  },
  {
    name: 'icestorm',
    tier: 6,
  },
  {
    name: 'fish',
    tier: 6,
  },
  {
    name: 'coin',
    tier: 6,
  },
  {
    name: 'yacht',
    tier: 6,
  },
  {
    name: 'party',
    tier: 6,
  },
  {
    name: 'tshirt',
    tier: 6,
  },
  {
    name: 'whale',
    tier: 7,
  },
] as { name: ElementName; tier: number }[];
