#!/usr/bin/env bash

set -e pipefail

cd ~/services/elementerra-index
git pull
npm ci
npm run build
RELATIONAL_DATABASE_HOST='__RELATIONAL_DATABASE_HOST__' \
  RELATIONAL_DATABASE_PORT='5432' \
  RELATIONAL_DATABASE_USERNAME='__RELATIONAL_DATABASE_USERNAME__' \
  RELATIONAL_DATABASE_PASSWORD='__RELATIONAL_DATABASE_PASSWORD__' \
  RELATIONAL_DATABASE_NAME='__RELATIONAL_DATABASE_NAME__' \
  OBJECT_DATABASE_HOST='__OBJECT_DATABASE_HOST__' \
  OBJECT_DATABASE_PORT='27017' \
  OBJECT_DATABASE_USERNAME='__OBJECT_DATABASE_USERNAME__' \
  OBJECT_DATABASE_PASSWORD='__OBJECT_DATABASE_PASSWORD__' \
  OBJECT_DATABASE_NAME='__OBJECT_DATABASE_NAME__' \
  PAIN_TEXT_PASSWORD='__PAIN_TEXT_PASSWORD__' \
  /home/admin/.local/bin/pm2 \
  restart ~/services/elementerra-index/dist/main.js \
  --update-env
