name: Deploy Service

on:
  push:
    branches: ['main']
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fill update deployment script with secrets
        run: |
          sed -i \
            -e "s|__RELATIONAL_DATABASE_HOST__|${{ secrets.RELATIONAL_DATABASE_HOST }}|g" \
            -e "s|__RELATIONAL_DATABASE_USERNAME__|${{ secrets.RELATIONAL_DATABASE_USERNAME }}|g" \
            -e "s|__RELATIONAL_DATABASE_PASSWORD__|${{ secrets.RELATIONAL_DATABASE_PASSWORD }}|g" \
            -e "s|__RELATIONAL_DATABASE_NAME__|${{ secrets.RELATIONAL_DATABASE_NAME }}|g" pull_and_deploy.sh

      - name: Trigger deployment on host
        run: ssh admin@${{ secrets.DEPLOYMENT_HOST }} 'bash -s' < pull_and_deploy.sh
